name: Python package and test

on:
  push:
  pull_request:

jobs:
  checkout-test:
    name: Checkout and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-latest"]
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create python 3.11 conda env
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11
          mamba-version: "*"
          activate-environment: donkey
          auto-activate-base: false
          channels: default, conda-forge, pytorch
          channel-priority: true
      - name: Conda info and list
        run: |
          conda info
          conda list
      - name: Install donkey
        run: | 
          pip install -e .[pc,dev]
          pip list
      - name: Run tests
        run: pytest
